---
- name: Download and Unarchive a file that is already on the remote machine
  unarchive:
    src: "https://github.com/rancher/cli/releases/download/{{ rancher_cli_version }}/rancher-linux-amd64-{{ rancher_cli_version }}.tar.gz" 
    dest: "/tmp"
    remote_src: yes

- name: copy to path
  copy:
    src: "/tmp/rancher-{{ rancher_cli_version }}/rancher"
    dest: "{{ rancher_cli_install_dir }}/rancher"
    mode: a+x
    remote_src: yes
  become: yes
